---
- name: Write default config
  notify:
    - Restart rabbitmq-exporter
  ansible.builtin.template:
    src: default.j2
    dest: /etc/default/rabbitmq-exporter
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - rabbitmq-exporter

- name: Prepare service file
  notify:
    - Restart rabbitmq-exporter
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/rabbitmq-exporter.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - rabbitmq-exporter

- name: Pull docker image
  when:
    - rabbitmq_exporter_pull_image
  community.docker.docker_image:
    name: "{{ rabbitmq_exporter_image }}"
    source: pull
  tags:
    - rabbitmq-exporter

- name: Create docker network
  when:
    - false if rabbitmq_exporter_network is none else (rabbitmq_exporter_network | length > 0)
  community.docker.docker_network:
    name: "{{ rabbitmq_exporter_network }}"
  tags:
    - rabbitmq-exporter

- name: Start exporter service
  ansible.builtin.systemd:
    name: rabbitmq-exporter
    state: started
    daemon_reload: true
    masked: false
    enabled: true
  tags:
    - rabbitmq-exporter

...
