---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: release

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'rolehippie'

    steps:
      - name: Checkout source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Write buildtime
        run: date >| .github/RELEASE

      - name: Install releaser
        run: |
          npm install -g \
            conventional-changelog-conventionalcommits@6.1.0 \
            semantic-release@23.1.1 \
            @semantic-release/changelog \
            @semantic-release/git

      - name: Run releaser
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
<<<<<<< HEAD
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits@6.1.0

      - name: Write buildtime
        run: date >| .github/RELEASEDATE

      - name: Commit changes
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          author_name: GitHub Actions
          author_email: github@webhippie.de
          add: .github/RELEASEDATE
          message: "docs: automated release update [skip ci]"
          push: true
          commit: --signoff
=======
        run: semantic-release
>>>>>>> 9bda87f (ci: update release process and add schema to workflows)

...
